<?php

return [
    'name' => 'Sparkxe',
    'asset_path' => 'website/assets',
    'title' => 'Sparkxe — Digital Solutions Company',
    'description' => 'Sparkxe — digital marketing, custom software, mobile apps, e-commerce, ERP, and full-stack digital solutions for modern businesses.',
    'email' => 'hello@sparkxe.com',
    'phone' => '+1 (234) 567-890',
    'phone_link' => '+1234567890',
    'whatsapp' => '1234567890',
    'whatsapp_message' => 'Hi Sparkxe, I need help with a project',
    'default_theme' => 'spark',
    'themes' => [
        'spark' => 'Spark theme',
        'ocean' => 'Ocean theme',
        'sunset' => 'Sunset theme',
        'violet' => 'Violet theme',
        'forest' => 'Forest theme',
        'rose' => 'Rose theme',
        'midnight' => 'Midnight theme',
        'copper' => 'Copper theme',
        'arctic' => 'Arctic theme',
        'neon' => 'Neon theme',
    ],
    'social' => [
        'facebook' => '#',
        'twitter' => '#',
        'instagram' => '#',
        'linkedin' => '#',
    ],
    'specialization_services' => [
        ['slug' => 'digital-marketing', 'icon' => 'fa-solid fa-bullhorn', 'title' => 'Digital Marketing', 'description' => 'SEO, paid ads, and lead funnels that turn traffic into paying customers.'],
        ['slug' => 'pos-software', 'icon' => 'fa-solid fa-cash-register', 'title' => 'POS Software', 'description' => 'Fast billing, inventory tracking, and sales reports for retail and restaurants.'],
        ['slug' => 'mobile-apps', 'icon' => 'fa-solid fa-mobile-screen', 'title' => 'Android & iOS Apps', 'description' => 'Native and cross-platform mobile apps built for performance and scale.'],
        ['slug' => 'business-website', 'icon' => 'fa-solid fa-globe', 'title' => 'Business Website', 'description' => 'Professional websites that build trust and convert visitors into leads.'],
        ['slug' => 'custom-software', 'icon' => 'fa-solid fa-code', 'title' => 'Custom Software', 'description' => 'Tailored systems designed around your workflows, teams, and goals.'],
        ['slug' => 'e-commerce', 'icon' => 'fa-solid fa-cart-shopping', 'title' => 'E-commerce', 'description' => 'Online stores with secure payments, product management, and analytics.'],
        ['slug' => 'whatsapp-chatbot', 'icon' => 'fa-brands fa-whatsapp', 'title' => 'WhatsApp Marketing & Chatbot', 'description' => 'Automated replies, broadcast campaigns, and 24/7 customer support on WhatsApp.'],
        ['slug' => 'erp-software', 'icon' => 'fa-solid fa-chart-line', 'title' => 'ERP Software', 'description' => 'Unify finance, inventory, HR, and operations in one powerful dashboard.'],
    ],
    'service_mega_menu' => [
        'Software' => ['software'],
        'Marketing' => ['marketing'],
        'Design & Web' => ['web', 'design'],
    ],
    'services' => [
        [
            'slug' => 'digital-marketing',
            'icon' => 'fa-solid fa-bullhorn',
            'title' => 'Digital Marketing',
            'subtitle' => 'SEO, ads & lead generation',
            'category' => 'marketing',
            'counter' => 98,
            'description' => 'Sparkxe helps businesses grow online with data-driven digital marketing — from search visibility and paid campaigns to landing pages that convert visitors into qualified leads.',
            'features' => [
                'Search engine optimization (SEO) & local SEO',
                'Google Ads, Meta Ads & retargeting campaigns',
                'Lead generation funnels & landing pages',
                'Email marketing & automation workflows',
                'Analytics, conversion tracking & monthly reports',
            ],
            'process' => [
                ['title' => 'Audit & Strategy', 'text' => 'We review your market, competitors, and current channels to build a focused growth plan.'],
                ['title' => 'Campaign Setup', 'text' => 'Ads, tracking, content, and landing pages are configured for measurable results.'],
                ['title' => 'Optimize & Scale', 'text' => 'We refine campaigns weekly and scale what delivers the best ROI.'],
            ],
        ],
        [
            'slug' => 'pos-software',
            'icon' => 'fa-solid fa-cash-register',
            'title' => 'POS Software',
            'subtitle' => 'Billing & inventory systems',
            'category' => 'software',
            'counter' => 96,
            'description' => 'Fast, reliable point-of-sale systems for retail, restaurants, and multi-branch businesses. Sparkxe builds POS software that speeds up billing, tracks stock in real time, and gives you clear sales insights.',
            'features' => [
                'Quick billing & barcode scanning',
                'Inventory & stock alerts',
                'Multi-branch & multi-user access',
                'Sales, tax & profit reports',
                'Receipt printing & payment integrations',
            ],
            'process' => [
                ['title' => 'Workflow Mapping', 'text' => 'We document how your shop or restaurant operates day to day.'],
                ['title' => 'Build & Integrate', 'text' => 'POS screens, inventory, and reports are tailored to your setup.'],
                ['title' => 'Train & Launch', 'text' => 'Staff training and on-site or remote go-live support included.'],
            ],
        ],
        [
            'slug' => 'mobile-apps',
            'icon' => 'fa-solid fa-mobile-screen',
            'title' => 'Android & iOS Apps',
            'subtitle' => 'Mobile apps for any platform',
            'category' => 'software',
            'counter' => 97,
            'description' => 'Native and cross-platform mobile applications for Android and iOS. From customer-facing apps to internal business tools, Sparkxe delivers smooth performance, secure backends, and app store readiness.',
            'features' => [
                'Android & iOS native or cross-platform builds',
                'User authentication & push notifications',
                'API integrations & real-time features',
                'App Store & Play Store submission support',
                'Maintenance, updates & performance monitoring',
            ],
            'process' => [
                ['title' => 'Discovery', 'text' => 'We define features, user flows, and technical architecture.'],
                ['title' => 'Design & Develop', 'text' => 'UI/UX design followed by agile development sprints.'],
                ['title' => 'Test & Publish', 'text' => 'QA across devices, then launch to stores with documentation.'],
            ],
        ],
        [
            'slug' => 'business-website',
            'icon' => 'fa-solid fa-globe',
            'title' => 'Business Website',
            'subtitle' => 'Corporate & portfolio sites',
            'category' => 'web',
            'counter' => 99,
            'description' => 'Professional business websites that establish credibility and turn visitors into customers. Sparkxe designs responsive corporate sites and portfolios optimized for speed, SEO, and lead capture.',
            'features' => [
                'Custom responsive design',
                'Service & portfolio pages',
                'Contact forms & WhatsApp integration',
                'SEO-ready structure & fast loading',
                'SSL, hosting setup & launch support',
            ],
            'process' => [
                ['title' => 'Plan Content', 'text' => 'Sitemap, wireframes, and brand-aligned copy structure.'],
                ['title' => 'Design & Build', 'text' => 'Pixel-perfect pages built for desktop and mobile.'],
                ['title' => 'Launch & SEO', 'text' => 'Go live with analytics, search setup, and handover docs.'],
            ],
        ],
        [
            'slug' => 'custom-software',
            'icon' => 'fa-solid fa-code',
            'title' => 'Custom Software',
            'subtitle' => 'Built for your exact needs',
            'category' => 'software',
            'counter' => 95,
            'description' => 'When off-the-shelf tools do not fit, Sparkxe builds custom software around your workflows — dashboards, internal tools, automation, and integrations that save time and reduce errors.',
            'features' => [
                'Requirements analysis & technical planning',
                'Web-based admin panels & dashboards',
                'Third-party API & payment integrations',
                'Role-based access & audit logs',
                'Ongoing support & feature enhancements',
            ],
            'process' => [
                ['title' => 'Scoping', 'text' => 'Detailed requirements, timeline, and fixed or phased delivery plan.'],
                ['title' => 'Development', 'text' => 'Iterative builds with demos so you see progress early.'],
                ['title' => 'Deploy & Support', 'text' => 'Production deployment, training, and maintenance options.'],
            ],
        ],
        [
            'slug' => 'e-commerce',
            'icon' => 'fa-solid fa-cart-shopping',
            'title' => 'E-commerce',
            'subtitle' => 'Online stores that sell',
            'category' => 'web',
            'counter' => 97,
            'description' => 'Full e-commerce solutions with product catalogs, secure checkout, order management, and marketing integrations. Sparkxe builds online stores that are easy to manage and built to convert.',
            'features' => [
                'Product catalog & category management',
                'Payment gateway & shipping integrations',
                'Order tracking & customer accounts',
                'Discount codes & promotional campaigns',
                'Mobile shopping experience & analytics',
            ],
            'process' => [
                ['title' => 'Store Planning', 'text' => 'Products, payments, shipping, and admin workflow defined upfront.'],
                ['title' => 'Build Storefront', 'text' => 'Design, development, and payment testing completed end to end.'],
                ['title' => 'Go Live', 'text' => 'Launch with inventory import help and staff training.'],
            ],
        ],
        [
            'slug' => 'whatsapp-chatbot',
            'icon' => 'fa-brands fa-whatsapp',
            'title' => 'WhatsApp Chatbot',
            'subtitle' => 'Marketing & auto-replies',
            'category' => 'marketing',
            'counter' => 94,
            'description' => 'Automate customer conversations on WhatsApp with smart chatbots, broadcast campaigns, and 24/7 auto-replies. Sparkxe connects WhatsApp Business API to your sales and support workflows.',
            'features' => [
                'WhatsApp Business API setup',
                'Automated replies & conversation flows',
                'Broadcast & promotional campaigns',
                'Lead capture & CRM handoff',
                'Order updates & support ticket routing',
            ],
            'process' => [
                ['title' => 'Flow Design', 'text' => 'Map common customer questions and sales journeys.'],
                ['title' => 'Bot Build', 'text' => 'Configure automations, templates, and integrations.'],
                ['title' => 'Launch & Monitor', 'text' => 'Go live with analytics and ongoing optimization.'],
            ],
        ],
        [
            'slug' => 'erp-software',
            'icon' => 'fa-solid fa-chart-line',
            'title' => 'ERP Software',
            'subtitle' => 'Finance, HR & operations',
            'category' => 'software',
            'counter' => 93,
            'description' => 'Enterprise resource planning systems that unify finance, inventory, HR, and operations in one dashboard. Sparkxe delivers ERP solutions scaled to SMEs and growing enterprises.',
            'features' => [
                'Finance, invoicing & expense tracking',
                'Inventory & procurement modules',
                'HR, payroll & attendance (optional)',
                'Multi-branch reporting & dashboards',
                'Custom modules & third-party integrations',
            ],
            'process' => [
                ['title' => 'Process Review', 'text' => 'We map departments, data flows, and reporting needs.'],
                ['title' => 'Module Build', 'text' => 'Phased rollout of finance, stock, and operations modules.'],
                ['title' => 'Migration & Training', 'text' => 'Data migration, user training, and post-launch support.'],
            ],
        ],
        [
            'slug' => 'dynamic-website',
            'icon' => 'fa-solid fa-laptop-code',
            'title' => 'Dynamic Website',
            'subtitle' => 'CMS & interactive portals',
            'category' => 'web',
            'counter' => 98,
            'description' => 'Content-managed and interactive websites that you can update without coding. Sparkxe builds dynamic portals, member areas, and CMS-driven sites with admin panels tailored to your team.',
            'features' => [
                'Custom admin panel / CMS',
                'Blog, news & content publishing',
                'User registration & member portals',
                'Search, filters & dynamic listings',
                'Role-based content management',
            ],
            'process' => [
                ['title' => 'Content Architecture', 'text' => 'Define content types, users, and admin permissions.'],
                ['title' => 'Develop Portal', 'text' => 'Front-end experience plus backend management tools.'],
                ['title' => 'Handover', 'text' => 'Training for your team to publish and manage content.'],
            ],
        ],
        [
            'slug' => 'web-hosting',
            'icon' => 'fa-solid fa-server',
            'title' => 'Web Hosting',
            'subtitle' => 'Fast, secure & reliable hosting',
            'category' => 'web',
            'counter' => 99,
            'description' => 'Secure, high-performance hosting for business websites, e-commerce stores, and web applications. Sparkxe provides setup, SSL, backups, monitoring, and ongoing server management.',
            'features' => [
                'SSD hosting & CDN options',
                'Free SSL certificates',
                'Daily backups & uptime monitoring',
                'Email hosting & DNS management',
                'Migration from existing host included',
            ],
            'process' => [
                ['title' => 'Assess Needs', 'text' => 'Traffic, storage, and application requirements reviewed.'],
                ['title' => 'Setup Server', 'text' => 'Hosting provisioned, SSL configured, and site migrated.'],
                ['title' => 'Monitor', 'text' => 'Ongoing performance checks and support when you need help.'],
            ],
        ],
        [
            'slug' => 'social-media-handling',
            'icon' => 'fa-solid fa-share-nodes',
            'title' => 'Social Media Handling',
            'subtitle' => 'Content, posts & engagement',
            'category' => 'marketing',
            'counter' => 96,
            'description' => 'Consistent social media presence with planned content, creative posts, and community engagement. Sparkxe manages your brand across Facebook, Instagram, LinkedIn, and more.',
            'features' => [
                'Monthly content calendar & post design',
                'Copywriting & hashtag strategy',
                'Community replies & engagement',
                'Stories, reels & campaign creatives',
                'Performance reports & growth insights',
            ],
            'process' => [
                ['title' => 'Brand Voice', 'text' => 'Define tone, visuals, and posting frequency per platform.'],
                ['title' => 'Create & Schedule', 'text' => 'Design creatives and schedule posts for the month.'],
                ['title' => 'Engage & Report', 'text' => 'Monitor comments, respond promptly, and share metrics.'],
            ],
        ],
        [
            'slug' => 'logo-design',
            'icon' => 'fa-solid fa-pen-nib',
            'title' => 'Logo Design',
            'subtitle' => 'Memorable brand identities',
            'category' => 'design',
            'counter' => 100,
            'description' => 'Distinctive logo designs that capture your brand personality and work across print and digital. Sparkxe delivers logo concepts, revisions, and full brand-ready file packages.',
            'features' => [
                'Multiple initial concept directions',
                'Unlimited revisions within scope',
                'Vector source files (AI, SVG, PDF)',
                'Color & monochrome variations',
                'Social media & favicon sizes',
            ],
            'process' => [
                ['title' => 'Brief & Research', 'text' => 'Understand your brand, audience, and competitors.'],
                ['title' => 'Concepts', 'text' => 'Present logo directions for your feedback.'],
                ['title' => 'Finalize', 'text' => 'Polish chosen design and deliver all file formats.'],
            ],
        ],
        [
            'slug' => 'poster-design',
            'icon' => 'fa-solid fa-image',
            'title' => 'Poster Design',
            'subtitle' => 'Print & digital creatives',
            'category' => 'design',
            'counter' => 97,
            'description' => 'Eye-catching posters and promotional creatives for events, sales, social media, and print. Sparkxe designs on-brand visuals that grab attention and drive action.',
            'features' => [
                'Event, sale & campaign posters',
                'Social media ad creatives',
                'Print-ready & digital formats',
                'Brand-consistent typography & colors',
                'Fast turnaround for promotions',
            ],
            'process' => [
                ['title' => 'Creative Brief', 'text' => 'Goals, message, sizes, and references captured.'],
                ['title' => 'Design Drafts', 'text' => 'Initial layouts shared for review and feedback.'],
                ['title' => 'Export', 'text' => 'Final files delivered for print or online use.'],
            ],
        ],
        [
            'slug' => 'ui-ux-design',
            'icon' => 'fa-solid fa-bezier-curve',
            'title' => 'UI/UX Design',
            'subtitle' => 'Interfaces users love',
            'category' => 'design',
            'counter' => 98,
            'description' => 'User-centered UI/UX design for websites, mobile apps, and dashboards. Sparkxe creates intuitive interfaces that improve usability, trust, and conversion rates.',
            'features' => [
                'User research & persona development',
                'Wireframes & interactive prototypes',
                'Visual UI design systems',
                'Mobile-first responsive layouts',
                'Usability testing & design handoff to dev',
            ],
            'process' => [
                ['title' => 'Research', 'text' => 'Understand users, goals, and pain points.'],
                ['title' => 'Prototype', 'text' => 'Wireframes and clickable prototypes for validation.'],
                ['title' => 'Visual Design', 'text' => 'High-fidelity screens ready for development.'],
            ],
        ],
    ],
    'portfolio_items' => [
        ['tag' => 'E-commerce', 'title' => 'Fashion Retail Store', 'description' => 'Full online shop with payment gateway and WhatsApp orders.', 'slug' => 'e-commerce'],
        ['tag' => 'POS Software', 'title' => 'Restaurant POS System', 'description' => 'Multi-branch billing, kitchen display, and sales reports.', 'slug' => 'pos-software'],
        ['tag' => 'Mobile App', 'title' => 'Delivery Service App', 'description' => 'Android & iOS app with real-time tracking.', 'slug' => 'mobile-apps'],
        ['tag' => 'ERP', 'title' => 'Inventory ERP Suite', 'description' => 'Stock, finance, and HR in one dashboard.', 'slug' => 'erp-software'],
        ['tag' => 'Marketing', 'title' => 'Brand Launch Campaign', 'description' => 'Social media, ads, and landing page — 3x lead growth.', 'slug' => 'digital-marketing'],
        ['tag' => 'Website', 'title' => 'Corporate Business Site', 'description' => 'Modern responsive website with CMS and SEO.', 'slug' => 'business-website'],
    ],
    'blog_posts' => [
        [
            'tag' => 'Marketing',
            'date' => 'June 10, 2026',
            'read_time' => '5 min read',
            'title' => '5 Digital Marketing Strategies That Actually Work in 2026',
            'excerpt' => 'Learn how SEO, social ads, and WhatsApp campaigns can bring real customers to your business.',
        ],
        [
            'tag' => 'Software',
            'date' => 'June 5, 2026',
            'read_time' => '7 min read',
            'title' => 'When Your Business Needs Custom Software (Not a Template)',
            'excerpt' => 'POS, ERP, and bespoke apps save time and money — here\'s how to know when you\'re ready.',
        ],
        [
            'tag' => 'Design',
            'date' => 'May 28, 2026',
            'read_time' => '4 min read',
            'title' => 'UI/UX Mistakes That Cost You Customers — And How to Fix Them',
            'excerpt' => 'Simple design improvements that boost trust, usability, and conversion on any website or app.',
        ],
    ],
    'pricing_plans' => [
        [
            'name' => 'Starter',
            'description' => 'Perfect for new businesses going online',
            'price' => '$499',
            'price_suffix' => '/project',
            'featured' => false,
            'badge' => null,
            'button_class' => 'btn-outline',
            'button_text' => 'Get Started',
            'features' => [
                'Business website (up to 5 pages)',
                'Logo & basic brand kit',
                'Social media setup',
                '1 month web hosting',
                'Mobile responsive design',
            ],
        ],
        [
            'name' => 'Business',
            'description' => 'For growing companies that need more power',
            'price' => '$1,499',
            'price_suffix' => '/project',
            'featured' => true,
            'badge' => 'Most Popular',
            'button_class' => 'btn-default',
            'button_text' => 'Get Started',
            'features' => [
                'Dynamic website or e-commerce store',
                'Digital marketing setup',
                'WhatsApp chatbot integration',
                'UI/UX design & poster creatives',
                '3 months support & hosting',
            ],
        ],
        [
            'name' => 'Enterprise',
            'description' => 'Custom software & large-scale solutions',
            'price' => 'Custom',
            'price_suffix' => null,
            'featured' => false,
            'badge' => null,
            'button_class' => 'btn-outline',
            'button_text' => 'Request Quote',
            'features' => [
                'POS, ERP & custom software',
                'Android & iOS applications',
                'Dedicated project manager',
                'API integrations & automation',
                'Priority support & maintenance',
            ],
        ],
    ],
    'faqs' => [
        [
            'question' => 'What services does Sparkxe offer?',
            'answer' => 'We offer digital marketing, POS software, mobile apps, business websites, custom software, e-commerce, WhatsApp chatbots, ERP systems, web hosting, social media management, logo design, poster design, and UI/UX — all under one roof.',
            'active' => true,
        ],
        [
            'question' => 'How long does a typical project take?',
            'answer' => 'A business website usually takes 2–4 weeks. E-commerce and custom software projects range from 4–12 weeks depending on complexity. We\'ll give you a clear timeline before we start.',
            'active' => false,
        ],
        [
            'question' => 'Do you provide ongoing support after launch?',
            'answer' => 'Yes. All plans include post-launch support. We also offer monthly maintenance packages for hosting, updates, marketing, and feature additions.',
            'active' => false,
        ],
        [
            'question' => 'Can you work with businesses outside my city?',
            'answer' => 'Absolutely. We work with clients remotely across regions. Video calls, shared project boards, and regular updates keep everything transparent no matter where you are.',
            'active' => false,
        ],
        [
            'question' => 'How do I get a custom quote for ERP or POS software?',
            'answer' => 'Fill out the contact form below or email us. We\'ll schedule a short discovery call to understand your workflow, then send a detailed proposal with scope, timeline, and pricing.',
            'active' => false,
        ],
    ],
];
